# Introduction to Reinforcement Learning 
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/eleni-vasilaki/rl-notes/blob/main/notebooks/01_introduction.ipynb)

## What Reinforcement Learning Tells Me About Happiness

I'd go so far as to say that there is no other machine learning technique as relevant to life as reinforcement learning. It is not only its origin—reinforcement learning is rooted in psychological experiments—but also the fact that reinforcement learning ideas can be found in philosophical documents dating back to at least the time of Plato. Even today, reinforcement learning can tell me how to achieve happiness.

If you think I am biased, I will agree with you. This is my interpretation of the philosophical texts I have read, the technical books I teach, my studies on reinforcement learning, and—of course—my own experiences. Thus, I am going to start from Epicurus, who is one of my favourite philosophers because he is misunderstood as a hedonist, while he was actually practising and teaching a theory akin to reinforcement learning.

Epicurus believed in optimising a reward function across one’s life. He explicitly said that pursuing the pleasures of the flesh is not the point. For the exact phrasing, I will direct you to my other text **[Was Epicurus the Father of Reinforcement Learning?](https://arxiv.org/abs/1710.04582)**, which is based on my talk for our Machine Learning retreat in 2017. Back then, I thought that since I became the head of the Machine Learning group, I no longer needed to prove myself by giving technical talks. Besides, at 9:00 am, people would rather hear something different for a change. It was meant to be an amusing talk.

Epicurus suggests we should choose the actions that benefit our souls. This is a very interesting choice of words for someone who limited the presence of gods in his philosophy and who didn’t believe in the afterlife. I will therefore interpret avoiding actions that bring turmoil in our souls as what is good in the long run. Epicurus was suggesting that we also incorporate any future punishment that today’s pleasure will bring. If you have ever got drunk, you certainly know what I am talking about.

Please forgive me if I turn everything into an equation. I assure you that on the surface it is a most trivial one, though in its essence it is the meaning of it all. We can write the total returns of an action at time t to be:

$$
G(t) = R(t+1) + R(t + 2) + R(t + 3) + … + R(t + N)
$$

where $R(t)$ represents the reward-or, if negative, punishment-at time point $t$. Rewards can of course, be 0 meaning the absence of it. 

In writing this equation, I assume that I will eventually die, that my moments of pleasure and punishment are finite, and their importance doesn’t diminish with how far in the future they are. It is an important notion as I cannot maximise a function of infinite value. Otherwise, if I feel invincible, which I occasionally still do, I will have to write:

$$
G(t) = R(t+1) + R(t + 2)\gamma + R(t + 3)\gamma^2 + R(t + 4)\gamma^3 + …
$$

Now I can live forever, but there is a discount factor $\gamma$ multiplying each reward that I receive, a positive real number $\gamma < 1$, which is raised to a power depending on how far away in the future the reward is. This just tells me that the reward I receive now will always be better than the same amount of reward that I will get next year, and it explains why I am so impatient.

In the Epicurean philosophy, there are clear instructions or suggestions regarding the values of various actions. For instance, Epicurus’ advice is to pursue friendship rather than romance because the latter brings jealousy and pain. I will therefore write in an equation that the value of friendship is higher than the value of romance:

$$
Q(\text{friendship}) > Q(\text{romance})
$$

where $Q$ is the value of the action to be considered and is interpreted as the expected sum of all the future rewards (and punishments), discounted, of course, that can result from this action. Here, there is an omission: saying that the action is independent of our state is clearly an oversimplification. For instance, we can consider a state $S_t$ that includes our own "state of mind" and the other person involved at time $t$. The value of friendship itself must also depend on the person we choose to offer our friendship. A more complete statement is therefore:

$$
Q(S(t), \text{friendship}) > Q(S(t), \text{romance})
$$

You can argue that the correctness of this inequality may very well depend on the specific state $s$, but if I sample a state, on average this is more likely to be true. Of course, nobody says that $Q(S_t, \text{friendship})$ cannot have a very low value itself if investing in friendship with the wrong person, but it is likely to still be higher than $Q(S_t, \text{romance})$ if investing in romance with the same wrong person.

Implicit here is the investment in all these actions. Any action of friendship, or of anything else in fact, rarely comes for free: it typically involves some effort. In this framework, and to keep things simple, I may consider the investment as a negative reward, i.e., something that I pay now in order to get a higher return in the future. The update rule for learning the $Q$ values according to the well-known [SARSA algorithm](http://incompleteideas.net/book/the-book.html) is:

$$
\Delta Q(S_t, A_t) = \alpha \left( R(t+1) + \gamma Q(S_{t+1}, A_{t+1}) \right) - Q(S_t, A_t)
$$

which I can interpret as "total reward minus expected reward." The value $Q(S_t, A_t)$ is the expectation for immediate and future rewards that I will receive when I am in state $S_t$ and choose action $A_t$. If my prediction is correct, $Q(S_t, A_t)$ should be equal to the immediate reward I will receive as a consequence of my action  $R_{t+1}$ plus the $Q$ value of the future state-action pair $(S_{t+1}, A_{t+1})$, i.e., my expected reward for the future state $S_{t+1}$ when taking future action $A_{t+1}$, discounted. If my expectation is wrong, then the terms do not match, and I need to update $Q(S_t, A_t)$.

Given my investments on the way to my goal, represented as negative rewards, I need, and perhaps expect, future rewards that are large enough to compensate my investment and that arrive before they feel heavily discounted.

Therefore, receiving a smaller reward than anticipated can feel like punishment: the difference is negative. The film that your friend told you is amazing might disappoint you if you watch it with great expectations. Correspondingly, I remember watching the end of ["Lost"](https://en.wikipedia.org/wiki/Lost_(TV_series)) many years after its first airing, having often heard how awful it was. However, it didn’t seem quite as bad to me. You see, after all the negative comments I had heard, my expectations were pretty low.

In friendship or romance, or indeed anything else, great expectations and high investment are likely to lead to disappointment. Reinforcement learning suggests you should have low expectations in situations you cannot really control and should avoid over-investment. In doing so, any reward is more likely to feel rewarding and any punishment as less punishing.

Ongoing investments also lead to a natural bias in the perception of people. I, as an external observer for someone else, may be aware of signs of success (rewards) but I am likely unaware of their investments (punishments). On the contrary, I am perfectly aware of my own investments, and therefore any perception of my personal success may feel less to me than in the eyes of other people. Sometimes it may even feel like a punishment: since I consumed the punishment first, the success may not be enough to make up for it—after all, I am impatient!

This is how reinforcement learning tells me to live my life: enjoy simple things; do not expect too much from others; do not over-invest; and never underestimate the effort or investment that people made in reaching their goals. Is there an element of luck? Reinforcement learning says there is, though unless you are trapped in local maxima, you will eventually find the optimal solution given sufficient time. This, however, is a discussion for another time.

*Eleni*

**Acknowledgements:** I am grateful to Peter Dayan for his incredibly fast feedback (as always!) on the text above and for pointing me to the work of [Kent Berridge](https://www.ncbi.nlm.nih.gov/pubmed/28943891), who makes the distinction between “liking” vs “wanting,” as well as the work of [Robb Rutledge](https://www.ncbi.nlm.nih.gov/pubmed/25092308), a modern-day Epicurus who proposed a computational model of momentary subjective happiness. A special thanks goes to ChatGPT for their meticulous proofreading.


**Important note:** This material was developed with the invaluable assistance of generative AI, particularly ChatGPT and Claude. AI is a powerful tool for learning and exploration, and its use is encouraged. However, like any tool, it should be used thoughtfully—over-reliance can get in the way of understanding. This material can be opened directly in Google Colab using the button at the top. In Colab, Gemini is the default AI agent, which can assist with understanding and improving the code.

## A brief introduction to NumPy

**NumPy** is a fundamental library for numerical computing in Python. It provides the efficient, flexible multi-dimensional array object (`ndarray`) and a wide range of mathematical functions. In machine learning, data is most naturally represented as matrices because many machine learning algorithms (e.g. linear regression, neural networks, PCA) rely on linear algebra operations (e.g. matrix multiplication, transposition) that are highly optimized in NumPy. Datasets are also typically organized in matrices. NumPy’s support for vectorized computations means that operations on large datasets can be performed quickly without explicit loops. In what follows, familiarity with Python and the basics of Object-Oriented Programming (OOP) is assumed; however an **[OOP Primer](https://github.com/eleni-vasilaki/rl-notes/blob/main/notebooks/00_oop_primer.ipynb)** is provided that would be useful to review when reinforcement learning algorithms are introduced. The **[Official Python Tutorial](https://docs.python.org/3/tutorial/index.html)** can be used for revision or further learning.

### Mathematical Definitions:
A **vector** is an ordered collection of numbers, which can represent points in space, directions, or quantities.

- A **column vector** is written as:

$$
\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ v_3 \\ \vdots \\ v_n \end{bmatrix}
$$

- A **row vector** is written as:

$$
\mathbf{v} = [v_1, v_2, v_3, \dots, v_n]
$$

A **matrix** is a rectangular array of numbers arranged in rows and columns. In machine learning, matrices are used to represent datasets (where rows are data samples and columns are features), perform linear transformations, and facilitate operations like matrix multiplication for neural networks.

- A **matrix** is written as:

$$
\mathbf{A} = \begin{bmatrix} a_{11} & a_{12} & \dots & a_{1n} \\ a_{21} & a_{22} & \dots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \dots & a_{mn} \end{bmatrix}
$$

**Example**:

In [14]:
import numpy as np

# Define a column vector as a 2D array with shape (4, 1)
v = np.array([[1], [2], [3], [4]])

# Define a row vector as a 1D array with shape (4,)
v_row = np.array([1, 2, 3, 4])

print("Column vector:\n", v)
print("Shape of the column vector:", v.shape)

print("\nRow vector:", v_row)
print("Shape of the row vector:", v_row.shape)

Column vector:
 [[1]
 [2]
 [3]
 [4]]
Shape of the column vector: (4, 1)

Row vector: [1 2 3 4]
Shape of the row vector: (4,)


**Note:** In NumPy, a vector with shape `(n,)` is a 1-dimensional array. However, for matrix operations like dot products or when interfacing with ML models, we often require explicit 2-dimensional **column vectors** with shape `(n, 1)`.

The **`reshape(-1, 1)`** method reshapes the array while inferring the number of rows automatically. Here:  
- **`-1`** means *"infer this dimension based on the length of the array,"*  
- **`1`** means *"reshape it into a single column." 
- **Instead of** `1` you can give it another positive value **x** , assuming there are enough elements in the vector to fill exaclty **x** columns. 

When reshaping, **the elements are filled in row-major order (C-style order)**, which means:  
- **Elements are filled column-wise from the original array.**  
- The reshaped column vector maintains the same order of elements as the original row vector, just stacked vertically.

In [15]:
import numpy as np

v = np.array([1, 2, 3, 4])  # Shape (4,)
v_column = v.reshape(-1, 1)  # Reshape to (4, 1)

print(v_column)

[[1]
 [2]
 [3]
 [4]]


# Exercise: Initialising an $n$-dimensional vector with random numbers  

Generate a vector of length $n$ with random numbers between 0 and 1. Set $n$ to a small positive value. Convert it to dimensions $(n,1)$. Display the dimensions of the vector.  

**Hint:** Use `np.random.rand(n)`, which generates a vector of length $n$ with elements drawn from a uniform distribution over $[0, 1)$.  

In [16]:
# Motivation: use NumPy commands instead of manual loops for simpler, faster code.
# Your solution here


<details>
  <summary>Show Solution</summary>
  
  ```python
 # Initialising an n-dimensional vector with random numbers
n = 5  # Dimension of the vector
v = np.random.rand(n)  # Generating a vector with random numbers between 0 and 1

print("Random vector:", v)  # Display the random vector

# Checking the dimensions (shape) of the vector
# Shape (n,) indicates a 1-dimensional array with n elements
print("Shape of the vector:", v.shape)

# Converting a vector of shape (n,) to (n,1) (common in ML for matrix operations)
# Reshape (-1, 1) infers the correct number of rows automatically
v_column = v.reshape(-1, 1)
print("Shape of the vector after convertion:", v_column.shape)

print("Reshaped column vector:\n", v_column)  # Display the reshaped column vector
  ```
</details>

**Example:** 

In [17]:
import numpy as np

# Define a matrix explicitly
A = np.array([[1, 2, 3], [4, 5, 6]])  # A 2x3 matrix

m, n = A.shape
print(f"Matrix A:\n{A}\nDimensions: {m}x{n}")

# Initialise a matrix of zeros
B = np.zeros((2, 3))
print(f"\nMatrix B (zeros):\n{B}")

# Fill a matrix element-by-element: a[i,j] = i + j (1-indexed)
rows, cols = 3, 3
matrix = np.empty((rows, cols))

for i in range(1, rows + 1):
    for j in range(1, cols + 1):
        matrix[i - 1, j - 1] = i + j

print("\nFilled Matrix:\n", matrix)

Matrix A:
[[1 2 3]
 [4 5 6]]
Dimensions: 2x3

Matrix B (zeros):
[[0. 0. 0.]
 [0. 0. 0.]]

Filled Matrix:
 [[2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]


# Exercise: Initialising an $n \times m$ matrix with random numbers  

Generate a matrix with dimensions $3 \times 4$ and fill it with uniformly distributed numbers between 0 and 1.  

**Hint:** Use `np.random.rand(n, m)`, which generates an $n \times m$ matrix with elements drawn from a uniform distribution over $[0, 1)$.  

In [18]:
# Motivation: use NumPy broadcasting instead of manual loops for simpler, faster code.
# Your solution here


<details>
  <summary>Show Solution</summary>
  
  ```python
# Initialising a matrix with random numbers
# Matrix A with shape (3, 4), representing 3 samples with 4 features each
A = np.random.rand(3, 4)

print("Random matrix (3x4):\n", A)  # Display the random matrix

# Checking the dimensions (shape) of the matrix
print("Shape of the matrix:", A.shape)
  ```
</details>

### Fundamental Vector Operations

Below we revise key vector operations with examples.

#### Vector-Scalar Multiplication

For a vector $ \mathbf{v} \in \mathbb{R}^{n} $ and a scalar $ \alpha $,

$$
\alpha \mathbf{v} = \begin{bmatrix} \alpha v_1 \\ \alpha v_2 \\ \vdots \\ \alpha v_n \end{bmatrix}
$$

Each element of the vector is multiplied by the scalar.

**Example:** 

In [19]:
import numpy as np

# Define a vector and a scalar
v = np.array([1, 2, 3, 4, 5])
alpha = 3

# Multiply vector by scalar (element-wise)
scaled_v = alpha * v

print("Original vector:", v)
print("Scaled vector:", scaled_v)

Original vector: [1 2 3 4 5]
Scaled vector: [ 3  6  9 12 15]


#### Vector Addition

For two vectors $ \mathbf{u}, \mathbf{v} \in \mathbb{R}^{n} $,

$$
\mathbf{u} + \mathbf{v} = \begin{bmatrix} u_1 + v_1 \\ u_2 + v_2 \\ \vdots \\ u_n + v_n \end{bmatrix}
$$

Vector addition is performed **element-wise**.  

**Note:** In mathematics, vectors are typically written as **column vectors**, but in NumPy, 1D arrays have shape **$(n,)$**, meaning they are neither row nor column vectors explicitly.

**Example:** 

In [20]:
import numpy as np

# Define two vectors of the same size
u = np.array([1, 2, 3, 4, 5])
v = np.array([5, 4, 3, 2, 1])

# Element-wise vector addition
sum_vector = u + v

print("Vector u:", u)
print("Vector v:", v)
print("Sum u + v:", sum_vector)

Vector u: [1 2 3 4 5]
Vector v: [5 4 3 2 1]
Sum u + v: [6 6 6 6 6]


#### Dot Product
For two vectors $ \mathbf{u}, \mathbf{v} \in \mathbb{R}^{n} $, their **dot product** is defined as:

$$
\mathbf{u} \cdot \mathbf{v} = \sum_{i=1}^{n} u_i v_i
$$

The dot product results in a **scalar** value.

**Example:** 

In [21]:
import numpy as np

# Define two vectors of the same size
u = np.array([1, 2, 3, 4, 5])
v = np.array([5, 4, 3, 2, 1])

# Dot product: returns a scalar
dot_product = np.dot(u, v)

print("Dot Product u · v:", dot_product)

Dot Product u · v: 35


#### Outer Product

For two vectors $ \mathbf{u} \in \mathbb{R}^{m} $ and $ \mathbf{v} \in \mathbb{R}^{n} $, the **outer product** results in an $ m \times n $ matrix:

$$
\mathbf{M} = \mathbf{u} \otimes \mathbf{v} =
\begin{bmatrix}
u_1 v_1 & u_1 v_2 & \dots & u_1 v_n \\
u_2 v_1 & u_2 v_2 & \dots & u_2 v_n \\
\vdots & \vdots & \ddots & \vdots \\
u_m v_1 & u_m v_2 & \dots & u_m v_n
\end{bmatrix}
$$

Unlike the dot product, the outer product results in a **matrix**.

**Example:** 

In [22]:
import numpy as np

# Define two vectors - they can be of different sizes for the outer product
u = np.array([1, 2, 3, 4, 5, 6])
v = np.array([5, 4, 3, 2, 1])

# Outer product: returns an (m x n) matrix
outer_product = np.outer(u, v)

print("Outer Product:\n", outer_product)

Outer Product:
 [[ 5  4  3  2  1]
 [10  8  6  4  2]
 [15 12  9  6  3]
 [20 16 12  8  4]
 [25 20 15 10  5]
 [30 24 18 12  6]]


#### Hadamard (Element-wise) Product

For two vectors $ \mathbf{u}, \mathbf{v} \in \mathbb{R}^{n} $, their **Hadamard (element-wise) product** is:

$$
\mathbf{u} \circ \mathbf{v} = \begin{bmatrix} u_1 v_1 \\ u_2 v_2 \\ \vdots \\ u_n v_n \end{bmatrix}
$$

Unlike the dot product, the Hadamard product **preserves the shape of the original vectors**.

**Example:** 

In [23]:
import numpy as np

# Define two vectors of the same size
u = np.array([1, 2, 3, 4, 5])
v = np.array([5, 4, 3, 2, 1])

# Hadamard (element-wise) product: preserves shape
hadamard_product = u * v

print("Hadamard Product u ∘ v:", hadamard_product)

Hadamard Product u ∘ v: [5 8 9 8 5]


### Fundamental Matrix Operations

Below are key matrix operations with definitions, motivations, and examples.

#### Matrix-Vector Multiplication

For a matrix $ A \in \mathbb{R}^{m \times n} $ and a vector $ \mathbf{v} \in \mathbb{R}^{n} $,  
their multiplication results in another vector $ \mathbf{b} \in \mathbb{R}^{m} $:

$$
\mathbf{b} = A \mathbf{v}
$$

Explicitly:

$$
\begin{bmatrix} b_1 \\ b_2 \\ \vdots \\ b_m \end{bmatrix} =
\begin{bmatrix} a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn} \end{bmatrix}
\begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}
$$

Each element of $ \mathbf{b} $ is computed as:

$$
b_i = \sum_{j=1}^{n} a_{ij} v_j
$$

where each row of $ A $ is multiplied by the vector $ \mathbf{v} $.

**Example:** 

In [24]:
import numpy as np

# Define a 3x3 matrix and a compatible vector
A = np.array([[2, 1, 3],
              [4, 2, 1],
              [1, 5, 2]])

v = np.array([1, 2, 3])

# Matrix-vector multiplication: result is a vector
b = np.dot(A, v)

print("Matrix A:\n", A)
print("\nVector v:\n", v)
print("\nResult of A * v:\n", b)

Matrix A:
 [[2 1 3]
 [4 2 1]
 [1 5 2]]

Vector v:
 [1 2 3]

Result of A * v:
 [13 11 17]


#### Matrix-Matrix Multiplication

For two matrices $ A \in \mathbb{R}^{m \times n} $ and $ B \in \mathbb{R}^{n \times p} $,  
their multiplication results in a new matrix $ C \in \mathbb{R}^{m \times p} $:

$$
C = A B
$$

Explicitly:

$$
C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}
$$

where each row of $ A $ is multiplied by each column of $ B $.

**Example:** 

In [25]:
import numpy as np

# Define A (3x2) and B (2x3)
A = np.array([[2, 3],
              [1, 4],
              [3, 2]])

B = np.array([[1, 2, 3],
              [4, 5, 6]])

# Matrix-matrix multiplication using the @ operator
C = A @ B  # Equivalently: np.dot(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nResult of A @ B:\n", C)

Matrix A:
 [[2 3]
 [1 4]
 [3 2]]

Matrix B:
 [[1 2 3]
 [4 5 6]]

Result of A @ B:
 [[14 19 24]
 [17 22 27]
 [11 16 21]]


#### Hadamard (Element-wise) Product

For two matrices $ A, B \in \mathbb{R}^{m \times n} $,  
the Hadamard (element-wise) product is:

$$
(A \circ B)_{ij} = A_{ij} B_{ij}
$$

Unlike matrix multiplication, this operation is performed **element-wise**.

**Example:** 

In [26]:
import numpy as np

# Define two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Hadamard product (element-wise multiplication)
H = A * B

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nHadamard Product A ∘ B:\n", H)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Hadamard Product A ∘ B:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


#### Matrix Transpose

For a matrix $ A \in \mathbb{R}^{m \times n} $,  
its transpose $ A^T \in \mathbb{R}^{n \times m} $ is defined as:

$$
(A^T)_{ij} = A_{ji}
$$

which means the rows and columns of $ A $ are swapped.

**Example:** 

In [27]:
import numpy as np

# Define a 3x2 matrix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Two equivalent ways to compute the transpose
A_T = A.T
A_T_ = np.transpose(A)

print("Matrix A:\n", A)
print("\nTranspose of A:\n", A_T)
print("\nAgain, transpose of A:\n", A_T_)

Matrix A:
 [[1 2]
 [3 4]
 [5 6]]

Transpose of A:
 [[1 3 5]
 [2 4 6]]

Again, transpose of A:
 [[1 3 5]
 [2 4 6]]


# Exercise: Useful matrix identity 

An important and useful identity for machine learning is:

$$
(AB)^T = B^T A^T.
$$

This identity states that the **transpose of the product of two matrices** equals the **product of their transposes in reverse order**. It assumes that the matrices can be multiplied, meaning that **$A$ is an $m \times n$ matrix** and **$B$ is an $n \times p$ matrix**.

Use **pen and paper** (or type if you prefer) to **prove** this identity. You will need to use the **definitions of matrix multiplication and transposition** and show that the **left-hand side equals the right-hand side** of the equation.

<details>
  <summary>Show Solution</summary>
  
$$
(AB)_{ij} = \sum_{k=1}^{n} A_{ik}B_{kj}
$$

Taking the transpose of $AB$:
$$
[(AB)^T]_{ji} = (AB)_{ij} = \sum_{k=1}^{n} A_{ik}B_{kj}
$$

For the product $B^T A^T$:
$$
(B^T A^T)_{ji} = \sum_{k=1}^{n} (B^T)_{jk}(A^T)_{ki} = \sum_{k=1}^{n} B_{kj}A_{ik}
$$

Since matrix multiplication is commutative under addition:
$$
\sum_{k=1}^{n} A_{ik}B_{kj} = \sum_{k=1}^{n} B_{kj}A_{ik}
$$

Thus, proving $(AB)^T = B^T A^T$.

</details>


**Exercise:** Demonstrate $(AB)^T = B^T A^T$ using numerical examples.

In [28]:
# Motivation: transpose identity (AB)^T = B^T A^T underpins shape reasoning and backprop.
# Define matrices A and B

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# TODO: Compute AB
# AB = (A @ B) 

# TODO: Compute the transpose of AB
# AB_T = 

# TODO: Compute the transpose of A and B
# A_T = 
# B_T = 

# TODO: Compute B^T A^T
# B_T_A_T = 

# Verify (AB)^T = B^T A^T
# The assert statement checks if a condition is True.
# If True, execution continues. If False, it raises an AssertionError.
# assert np.array_equal(AB_T, B_T_A_T), "The identity does not hold."


<details>
  <summary>Show Solution</summary>
  
  ```python
# Define matrices A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute AB
AB = np.dot(A, B)

# Compute the transpose of AB
AB_T = np.transpose(AB)

# Compute the transpose of A and B
A_T = np.transpose(A)
B_T = np.transpose(B)

# Compute B^T A^T
B_T_A_T = np.dot(B_T, A_T)

# Verify (AB)^T = B^T A^T
#The assert statement in Python is used to check if a given condition is True. 
#If the condition is True, the program does nothing and moves to the next line of code. 
#However, if the condition is False, the program raises an AssertionError. 
#Optionally it can display a specified message.
assert np.array_equal(AB_T, B_T_A_T), "The identity does not hold."
  ```
</details>

# Exercise: Compare Matrix Multiplication Methods

Matrix multiplication is a fundamental operation in machine learning and numerical computing. There are different ways to compute it, and some are much faster than others.

In this exercise, you will:
1. Implement a function using the NumPy matrix multiplication operator.
2. Implement your own function for matrix multiplication using for-loops.
3. Measure and compare execution times for both methods.
4. Visualize the results using `matplotlib`.

Before we start, let's briefly introduce:
- The `timeit` module for measuring execution time,
- The `matplotlib` library for plotting results.

⏱ Measuring Execution Time with `timeit`

The `timeit` module helps measure how long a function takes to run.

```python
import timeit

def example_function():
    sum([i for i in range(1000)])  # List comprehension

# Using timeit with a lambda function to pass arguments correctly
time_taken = timeit.timeit(lambda: example_function(), number=100)
print("Execution time:", time_taken)
```
- **`number=100`** → Runs the function **100 times** and reports total time.
- **Dividing total time by 100** → Gives the **average execution time per run**.

Why Do We Use `lambda` in `timeit.timeit()`?
- `timeit.timeit()` expects a **function reference**, not a direct function call.
- If a function **has no parameters**, we can pass it directly:
  ```python
  timeit.timeit(example_function, number=100)  
  ```
- **But if a function requires arguments**, we **must use `lambda`** to delay execution:
  ```python
  timeit.timeit(lambda: example_function(5), number=100) 
  ```
- `lambda` ensures that the function is **only executed when `timeit` calls it**, rather than immediately.


Using `timeit` helps compare different implementations and find the most efficient approach.

---

 📊 Plotting Results with `matplotlib`

`matplotlib` is a library for creating visualizations and analyzing data trends.

```python
import matplotlib.pyplot as plt

# Sample data
x = [1, 2, 3, 4, 5]
y = [10, 20, 30, 40, 50]

# Create a line plot
plt.plot(x, y, label="Example Line")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Sample Plot")
plt.legend()
plt.show()
```
This will generate a **simple line plot** with labeled axes and a legend. `plt.show()` displays the graph.

In [29]:
# Motivation: compare vectorized NumPy vs pure Python loops to see why we prefer vectorization.
import numpy as np
import timeit
import matplotlib.pyplot as plt


def multiply_numpy(A, B):
    """Matrix multiplication using NumPy's optimised operator."""
    return A @ B


def multiply_loops(A, B):
    """Matrix multiplication using nested for-loops (inefficient)."""
    result = 0  # TODO: initialise result with correct shape
    # TODO: implement the triple nested loop
    return result


# Benchmarking
max_n = 100
numpy_times = np.zeros(max_n)
loop_times = np.zeros(max_n)

for size in range(1, max_n + 1):
    matrix1 = np.zeros((size, size))  # TODO: replace with random values
    matrix2 = np.zeros((size, size))  # TODO: replace with random values

    # Measure execution time for each method
    numpy_times[size - 1] = timeit.timeit(
        lambda: multiply_numpy(matrix1, matrix2), number=1
    )

# TODO: Plot execution times for both methods


<details>
  <summary>Show Solution</summary>
  
  ```python
import numpy as np
import timeit
import matplotlib.pyplot as plt

# Matrix multiplication using NumPy (efficient)
def multiply_numpy(A, B):
    assert A.shape[1] == B.shape[0], "Matrix dimensions do not match for multiplication!"
    return A @ B  # NumPy's optimized matrix multiplication

# Matrix multiplication using nested loops (inefficient)
def multiply_loops(A, B):
    assert A.shape[1] == B.shape[0], "Matrix dimensions do not match for multiplication!" 
    rows_A, cols = A.shape  
    cols, cols_B = B.shape  
    result = np.zeros((rows_A, cols_B))

    for i in range(rows_A):  
        for j in range(cols_B):  
            for k in range(cols):  
                result[i, j] += A[i, k] * B[k, j]  

    return result

# Benchmarking
max_n = 100  
numpy_times = np.zeros(max_n)
loop_times = np.zeros(max_n)

for size in range(1, max_n + 1):
    matrix1 = np.random.rand(size, size)
    matrix2 = np.random.rand(size, size)

    # Measure execution time using direct function calls (NumPy and loops)
    numpy_times[size - 1] = timeit.timeit(lambda: multiply_numpy(matrix1, matrix2), number=1)
    loop_times[size - 1] = timeit.timeit(lambda: multiply_loops(matrix1, matrix2), number=1)

# Plot execution times
plt.plot(range(1, max_n + 1), numpy_times, label="NumPy multiplication")
plt.plot(range(1, max_n + 1), loop_times, label="For-loop multiplication")

plt.xlabel("Matrix Size $n$")
plt.ylabel("Execution Time (seconds)")
plt.title("Performance: NumPy vs. For-Loops")
plt.legend()
plt.grid(True)
plt.show()
  ```
</details>

### Other Important Matrix Operations in NumPy

#### Matrix Slicing
Slicing allows you to extract specific rows, columns, or submatrices from a NumPy array.

Consider the **3×3 matrix** \( A \):

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

**Extracting the First Row**

$$
\text{Result: } \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}
$$

**Extracting the Second Column**

$$
\text{Result: }
\begin{bmatrix}
2 \\
5 \\
8
\end{bmatrix}
$$

**Extracting a 2×2 Submatrix**

$$
\text{Result: }
\begin{bmatrix}
2 & 3 \\
5 & 6
\end{bmatrix}
$$


**Example:** 

In [30]:
import numpy as np

# Create a 3x3 matrix
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Extract the first row (all columns)
row_1 = a[0, :]

# Extract the second column (all rows)
col_2 = a[:, 1]

# Extract a 2x2 submatrix (first two rows, last two columns)
submatrix = a[0:2, 1:3]

print("Original Matrix:\n", a)
print("\nFirst Row:\n", row_1)
print("\nSecond Column:\n", col_2)
print("\nSubmatrix:\n", submatrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

First Row:
 [1 2 3]

Second Column:
 [2 5 8]

Submatrix:
 [[2 3]
 [5 6]]


**Note** There is a difference between column vector representation in mathematics and Numpy.

#### Broadcasting
Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes without explicit looping.
Consider the **3×3 matrix** \( A \):

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

**Adding a Scalar to Every Element**

$$
A + 10 =
\begin{bmatrix}
11 & 12 & 13 \\
14 & 15 & 16 \\
17 & 18 & 19
\end{bmatrix}
$$


**Adding a Row Vector to Each Row**

$$
A +
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
=
\begin{bmatrix}
2 & 4 & 6 \\
5 & 7 & 9 \\
8 & 10 & 12
\end{bmatrix}
$$

**Example:** 

In [31]:
import numpy as np

b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Adding a scalar broadcasts to every element
b_plus_scalar = b+10
print("Matrix + 10:\n", b_plus_scalar)

# Adding a row vector broadcasts to each row of the matrix
row_vector = np.array([1, 2, 3])
broadcasted_sum = b + row_vector
print("\nMatrix + Row Vector:\n", broadcasted_sum)

Matrix + 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Matrix + Row Vector:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


#### Why Are Slicing and Broadcasting Useful?
- **Avoids explicit loops**, making operations more efficient.
- **Optimized for performance**, allowing large datasets to be processed faster.
- **Flexible operations** on arrays of different shapes without reshaping.

# Exercise: Matrix slicing and broadcasting 

1. Create a **5×5** NumPy matrix filled with numbers from **1 to 25**.
2. Extract the **middle 3×3 submatrix**.
3. Add **5 to all elements** in the submatrix using broadcasting.
4. Print the **original matrix** and the **modified matrix** to observe the changes.

In [32]:
# Motivation: use NumPy broadcasting instead of manual loops for simpler, faster code.
# Your solution here


<details>
  <summary><strong>Show Solution</strong></summary>

  ```python
  import numpy as np

  # Create a 5x5 matrix with values from 1 to 25
  matrix = np.arange(1, 26).reshape(5, 5)

  # Extract middle 3x3 submatrix
  submatrix = matrix[1:4, 1:4]

  # Add 5 to all elements in submatrix
  submatrix += 5

  # Print results
  print("Original Matrix:\n", matrix)
  ```
</details>